"""RSICC Phase 7 (CodeAug: Indian Urban & Seasonal Domain Adaptation) library."""

from .codeaug_dataset import (
    BiTemporalUnionGLIJitter,
    compute_gli,
    export_cider_idf,
    get_balanced_sampler,
    get_codeaug_transforms,
    load_cider_idf,
)
from .config import DataConfig, ModelConfig, RemoteCLIPConfig, TrainConfig
from .dataset import (
    CaptionCollate,
    LEVIRCCDataset,
    Vocabulary,
    build_image_transforms,
    build_remoteclip_transforms,
    build_vocabulary_from_annotations,
    get_levircc_loaders,
    load_levircc_annotations,
    split_samples_by_split,
)
from .metrics import (
    SentenceEmbeddingScorer,
    collect_references_and_predictions,
    compute_bleu_scores,
    compute_cider_scores,
    compute_meteor_scores,
    compute_rouge_l_scores,
    evaluate_caption_metrics,
    evaluate_full_test_with_per_sample_metrics,
    evaluate_model_on_loader,
    evaluate_single_pair_metrics,
    generate_caption_greedy,
    save_phase1_results,
)
from .models import (
    CodeAugConfig,
    CodeAugRSICCModel,
    QFormerTokenCompressor,
    VisualLoRALayer,
    bicubic_interpolate_pos_embed,
    inject_visual_lora,
    update_vit_pos_embed,
)
from .training import (
    build_criterion,
    build_optimizer_and_scheduler,
    generate_caption,
    get_checkpoint_epoch,
    load_best_metrics,
    load_best_model,
    load_checkpoint,
    prepare_teacher_forcing_inputs,
    save_checkpoint,
    train_epoch,
    validate,
    visualize_predictions,
)
from .utils import (
    cuda_device_is_compatible,
    denormalize_image,
    get_device,
    set_seed,
    setup_project_path,
    stack_image_pair,
)

__all__ = [
    # CodeAug Phase 7 Architecture
    "CodeAugConfig",
    "CodeAugRSICCModel",
    "QFormerTokenCompressor",
    "VisualLoRALayer",
    "inject_visual_lora",
    "bicubic_interpolate_pos_embed",
    "update_vit_pos_embed",
    # CodeAug Phase 7 Data & Samplers
    "get_codeaug_transforms",
    "compute_gli",
    "BiTemporalUnionGLIJitter",
    "get_balanced_sampler",
    "export_cider_idf",
    "load_cider_idf",
    # Shared Configs & Data Helpers
    "DataConfig",
    "ModelConfig",
    "RemoteCLIPConfig",
    "TrainConfig",
    "Vocabulary",
    "LEVIRCCDataset",
    "CaptionCollate",
    "get_levircc_loaders",
    "load_levircc_annotations",
    "split_samples_by_split",
    "build_vocabulary_from_annotations",
    "build_image_transforms",
    "build_remoteclip_transforms",
    # Training
    "train_epoch",
    "validate",
    "save_checkpoint",
    "load_checkpoint",
    "load_best_model",
    "load_best_metrics",
    "generate_caption",
    "visualize_predictions",
    "prepare_teacher_forcing_inputs",
    "build_criterion",
    "build_optimizer_and_scheduler",
    "get_checkpoint_epoch",
    # Metrics
    "SentenceEmbeddingScorer",
    "collect_references_and_predictions",
    "compute_bleu_scores",
    "compute_cider_scores",
    "compute_meteor_scores",
    "compute_rouge_l_scores",
    "evaluate_caption_metrics",
    "evaluate_model_on_loader",
    "evaluate_full_test_with_per_sample_metrics",
    "evaluate_single_pair_metrics",
    "save_phase1_results",
    "generate_caption_greedy",
    # Utils
    "setup_project_path",
    "set_seed",
    "get_device",
    "cuda_device_is_compatible",
    "stack_image_pair",
    "denormalize_image",
]
